/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AnalisisEspacial;

import java.awt.Image;
import javax.swing.ImageIcon;
import open.AbrirImagen;

/**
 *
 * @author Daniela
 */
public class GUIFiltrosEspaciales extends javax.swing.JFrame {

    /**
     * Creates new form GUIFiltrosEspaciales
     */
    public Image Original;
    public Image Modificada;
    
    private Image modificada;
    
    public GUIFiltrosEspaciales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider_Temperatura = new javax.swing.JSlider();
        jLabelImagenOriginal = new javax.swing.JLabel();
        jButton_AbrirImagen = new javax.swing.JButton();
        jLabel_ValorTemperatura = new javax.swing.JLabel();
        jSlider_Iluminacion = new javax.swing.JSlider();
        jLabel_ValorIluminacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSlider_Temperatura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_TemperaturaStateChanged(evt);
            }
        });

        jButton_AbrirImagen.setText("Abrir Imagen");
        jButton_AbrirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbrirImagenActionPerformed(evt);
            }
        });

        jSlider_Iluminacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_IluminacionStateChanged(evt);
            }
        });

        jLabel1.setText("Temperatura");

        jLabel2.setText("Iluminación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSlider_Temperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton_AbrirImagen)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel_ValorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabelImagenOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSlider_Iluminacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel_ValorIluminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_AbrirImagen)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelImagenOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSlider_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ValorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider_Iluminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_ValorIluminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AbrirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbrirImagenActionPerformed
        // TODO add your handling code here:
         this.Original = AbrirImagen.openImage();
          this.jLabelImagenOriginal.setIcon(new ImageIcon(this.Original.getScaledInstance(this.jLabelImagenOriginal.getWidth(), this.jLabelImagenOriginal.getHeight(), Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_jButton_AbrirImagenActionPerformed

    private void jSlider_TemperaturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_TemperaturaStateChanged
        // TODO add your handling code here:
         jSlider_Temperatura.setMaximum(255);
        if(this.Original!=null){
            jSlider_Temperatura.getValue();
            String v = ""+jSlider_Temperatura.getValue();
            this.jLabel_ValorTemperatura.setText(v);
            modificada = FiltrosEspaciales.modificarTemperatura(Original,jSlider_Temperatura.getValue());
            this.Modificada = modificada;
            this.jLabelImagenOriginal.setIcon(new ImageIcon(modificada.getScaledInstance(this.jLabelImagenOriginal.getWidth(),this.jLabelImagenOriginal.getHeight(),Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_jSlider_TemperaturaStateChanged

    private void jSlider_IluminacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_IluminacionStateChanged
        // TODO add your handling code here:
         jSlider_Temperatura.setMaximum(255);
        if(this.Original!=null){
        jSlider_Temperatura.getValue();
            String v = ""+jSlider_Iluminacion.getValue();
            this.jLabel_ValorIluminacion.setText(v);
            modificada = FiltrosEspaciales.iluminarImagen(Original,jSlider_Iluminacion.getValue());
            this.Modificada = modificada;
            this.jLabelImagenOriginal.setIcon(new ImageIcon(modificada.getScaledInstance(this.jLabelImagenOriginal.getWidth(),this.jLabelImagenOriginal.getHeight(),Image.SCALE_DEFAULT)));
        }
                                                
    }//GEN-LAST:event_jSlider_IluminacionStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFiltrosEspaciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFiltrosEspaciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFiltrosEspaciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFiltrosEspaciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFiltrosEspaciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AbrirImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImagenOriginal;
    private javax.swing.JLabel jLabel_ValorIluminacion;
    private javax.swing.JLabel jLabel_ValorTemperatura;
    private javax.swing.JSlider jSlider_Iluminacion;
    private javax.swing.JSlider jSlider_Temperatura;
    // End of variables declaration//GEN-END:variables
}
